name: Self Code Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  code-guardian:
    name: Code Guardian
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      
      - name: Install dependencies
        run: bun install
      
      - name: Build action
        run: bun run build
      
      - name: Run AI Code Review
        uses: ./
        with:
          token: ${{ github.token }}
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          pr_number: ${{ github.event.pull_request.number }}
          ai_provider: 'anthropic'
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          include_extensions: '.ts'
          exclude_extensions: '.test.ts,.spec.ts'
          include_paths: 'src/'
          exclude_paths: 'node_modules/,dist/'
          fail_action_if_review_failed: 'false' 